name: trainium2_diff_mem
description: PSUM -> SBUF -> StRAM -> LtRAM -> HBM (on-die StRAM/LtRAM)
instance: configs/instances/trn2_3xlarge.yaml

links_GBs:
  psum_sbuf: 2048
  sbuf_stram: 800
  stram_ltram: 600
  ltram_hbm: 2900

levels:
  - id: psum
    enabled: true
    tech: psum_trainium2
    scope: per_core
    capacity_bytes: 2097152

  - id: sbuf
    enabled: true
    tech: sbuf_trainium2
    scope: per_core
    capacity_bytes: 29360128

  - id: stram
    enabled: true
    tech: edram_1t1c
    scope: per_chip
    capacity_bytes: 134217728

  - id: ltram
    enabled: true
    tech: rram
    scope: per_chip
    capacity_bytes: 1073741824

  - id: hbm
    enabled: true
    tech: hbm_trainium2
    scope: per_chip

kernel:
  wipe_levels_on_boundary: [psum, sbuf]
