name: psum_trainium2
class: sram
volatile: true
retention_s: null
cell_density_bits_per_um2: 2.44

access:
  read_latency_ns: 1
  write_latency_ns: 1
  read_energy_pJ_per_bit: 0.04
  write_energy_pJ_per_bit: 0.04
